* plotline
  What's your name?
  [get name]
  go to main menu (RET to play, [settings])
    + (resize window for best experience?)

* settings
  + text speed
    + have an interactable display that prompts for int then shows you how fast your chosen text speed is.
    + have the sample text be randomly chosen from a list

* objects
  + class Entity
    + void tick()  # details what each enemy does each game tick
    + int id
    + class Fireball
      + class fireball
        + int iPos
        + int jPos
        + static int idGenerator
        + when making a new
        + void tick():
          + continue moving in a direction by updating i and j pos
          + maybe kill tomatoes when they're 1 block far away instead of right on top of?

  + abstract Enemy
    + int hp
    + class BossTomato
      + 3by3 'X' grid gets added to the map somewhere else (until it dies)
      + super hp = many idk
      + super tick(): attack player if they're too close (further range than Vine)
      + sits there looking menacing
    + abstract Spawnable  # things that get spawned
      + int iPos  # position vars in constructor decides where they spawn
      + int jPos
      + class Vine
        + super hp = 5 or smth
        + int maturity = -5 or smth
        + super tick():
          + when first added to arraylist enemies, spawn as a "crack" in the "floor"
          + alternates char '\' and char '/' until maturity = 0 or something
          + every so often, spawn a Tomato (by adding new Tomato(this.x, this.y) to some global arraylist of enemies)
          + damage player if they're too close
          + maturity++ each tick
        + first time talcum the alchemist sees one, they point out that the floor is cracking, move away maybe?
      + class Tomato
        + hp = 1
        + super tick():
         + tryMove towards player, deal damage if hit player (have player complain about acid the first time)
         + cant move into opaque objects, just like player

* combat game loop
  + do player thing
  + for enemy in enemies, enemy.tick()
  + for fireball in fireballs, fireball.tick()
  + check for aoe attack, if applicable

* misc ideas
  + ui: dialouge, map, input, objective
  + new thing
    + have all entities have i, jpos
    + have entities have boolean isAt(i,j) that detects if they are at those coords
    + all entities except for boss return true if params i,j = this.i,j
    + boss override: return true if params i,j are 1 or 0 away from boss.i,j
  + during tutorial, if you bump into devil
    + 1st time "Don't push me." 2nd: "Don't push me. Last warning." 3rd: throw error: "I warned you"
  + VERY IMPORTANT
    + make sure Vines cannot spawn inside the player. thats going to be some wonkily buggy code for sure
    + spawn Vine after processing player movement
    + after player move is processed, the spawned Vine should not be at player.i, j
    + player shouldn't be able to walk over cracked ground since its not the ground tile
    + brainstorming for player movement:
      + let Player extend Entity
      + let tryMove() be a method in Player
      + tryMove(direction)
          if player isn't at edge of map {  // simulates walls being immovable
            movePlayer(direction)
            for Entity in EntityList
              if this.overlaps(Entity)  // boolean overlaps(Entity e) {} should check if i,j of e same as i,j of this
                if Entity is a Tomato
                  damage player
                  delete Entity (the tomato) from EntityList  // write a func for this somewhere.
                                                              // use id to delete correct entity?
                else // so, Entity blocks movement
                  movePlayer back
                  break
          }

* dialouge
** for tutorial and backstory
You wake up. As you blink the blurriness away, you notice that you - pretty obviously - aren't standing behind your
cash register, bravely manning the fort of a rural Wyoming Dollar Tree in the middle of nowhere anymore. Instead,
you're sitting down on the edge of an operating table in the middle of ... a cave? And a lot of it looks like it's on
fire? Also, there's this dude just standing in front of you. He's impeccably dressed in a three piece suit and
sports some noticeably cloven hooves.

[name]: Oof oof ouchie head hurt what happening

Satan: Hey there [name]. I brought you down here because, well, God told me to. Something something His Plan something
something Chosen One - I wasn't really paying attention. But basically, now you can throw fire out of your hands. I
kinda had to scramble your brain to give you magic so uh lets get you on your feet again, yeah?

He snaps his fingers, and

[open UI]

[name]: whatsgoingon

Satan: Oh yeah that just lets the fire gremlins I put in your soul look around, don't worry about it. Here, let's just
start out with some walking, mm? Press [w], [a], [s], or [d] and then press [ENTER] to move up, left, down, or right.
(unlock wasd-RET movement)
(add "Move with [wasd] + [ENTER]" to objectives)

[player movement]

Satan: Ah look at how you walk! I did a great job. Now, press just [ENTER] to move in the direction you were last facing.
(unlock RET movement)
(add "Move with [ENTER]" to objectives)

[player movement]
// TODO NOTE: [ENTER] alone should always repeat the last action EXCEPT for when using flameburst
// since we want player to really feel the weight of keysmashing
Satan: Great! Alright, now lets test out your new powers. Press [SPACE] and then [ENTER]. 
(unlock fireball)
(add "Throw a fireball with [SPACE] + [ENTER]" to objectives)

[player fireball]

Satan: Yep, that's a fireball alright. Move around a bit to see it go in the direction that you shot it in.
(add "Move around a bit" to objectives)

[player movement x times]

Satan: Great, just wonderful. Alright now this might be a bit harder so {be sure you know what you're doing}. Type in at
least three characters, and then [ENTER] to throw out, like, a bunch of fire. This time, it'll only exist for one turn, 
though.
(unlock flameburst)
(add "Use a flameburst with a keysmash + [ENTER]" to objectives)

Satan: Aight you're good to go on your epic God adventure or whatever. See you later!
(change map to the Dollar Tree)

** for fight
Talcum: Oh hey you're back.

[name]: talctalctalcithinkijustsawthedevilandalsoicandofiremagicnow

Talcum: Oh ok. Anyways, there was this one dude that came in, looked like a bibically accurate angel? Interlocking gold
wheels with infinite eyes, floating because we don't care about gravity I guess. Right? So it came in through the front
door - you would've thought it would've busted through the ceiling or something, that was kinda anticlimatic - and it
started screeching something about a test and Chosen One and fire and my ears are still ringing and it zapped those 
tomato plants over there and I think they're evil now. I think you're supposed to kill it? Yeah good luck with that, 
my shift is over, this isn't my problem anymore bye.

As Talcum walks out the door, the writhing mass of vines and tomatoes lets out a roar (from where? tomatoes don't have
vocal cords) as several cracks open in the ground. A few tomatoes drop off of the main vine in the center. The flooring
sizzles and somewhat dissolves under their splattering juice as the tomatoes start hopping towards you. Like a pack
of kangaroos, or something.

